
import React from "react";
import PromptBar from "../dashboardComponent/PromptBar";
import Navbar from "../dashboardComponent/Navbar";


function DashBoard() {
  return (
    <div>
      <Navbar/>
      <hr className="mx-auto w-3/4 border-t-2 border-gray-500 mt-4"/>
       {/* here comes the output generated by the AI */}
      <div className=" static flex justify-center">
      <PromptBar/>
    </div>
    </div>
  );
}

export default DashBoard;
